/**
 * ============================================================================
 * CustomizedGradebook - PRODUCTION Loader
 * ============================================================================
 * This loader snippet injects the CustomizedGradebook script into Canvas.
 *
 * Structure:
 * - External loader code (stable, preserved)
 * - CG-managed block (regenerated by Admin Dashboard)
 */

(function () {
    // ========================================================================
    // EXTERNAL LOADER CODE (STABLE - DO NOT MODIFY MANUALLY)
    // ========================================================================

    // Initialize CG_CONFIG if not already present (allows pre-configuration)
    window.CG_CONFIG = window.CG_CONFIG || {};

    // Define configuration defaults
    const defaults = {
        // Feature flags
        ENABLE_STUDENT_GRADE_CUSTOMIZATION: true,

        // Grading mode configuration
        ENABLE_OUTCOME_UPDATES: true,
        ENABLE_GRADE_OVERRIDE: true,

        // UI labels and resource names
        UPDATE_AVG_BUTTON_LABEL: "Update Current Score",
        AVG_OUTCOME_NAME: "Current Score",
        AVG_ASSIGNMENT_NAME: "Current Score Assignment",
        AVG_RUBRIC_NAME: "Current Score Rubric",

        // Outcome configuration
        DEFAULT_MAX_POINTS: 4,
        DEFAULT_MASTERY_THRESHOLD: 3,

        // Rating scale for outcomes and rubrics
        OUTCOME_AND_RUBRIC_RATINGS: [
            { description: "Exemplary", points: 4 },
            { description: "Beyond Target", points: 3.5 },
            { description: "Target", points: 3 },
            { description: "Approaching Target", points: 2.5 },
            { description: "Developing", points: 2 },
            { description: "Beginning", points: 1.5 },
            { description: "Needs Partial Support", points: 1 },
            { description: "Needs Full Support", points: 0.5 },
            { description: "No Evidence", points: 0 }
        ],

        // Outcome filtering
        EXCLUDED_OUTCOME_KEYWORDS: ["Homework Completion"]
    };

    // Apply defaults only where keys are undefined
    for (const key in defaults) {
        if (window.CG_CONFIG[key] === undefined) {
            window.CG_CONFIG[key] = defaults[key];
        }
    }

    // Merge managed config if present
    if (window.CG_MANAGED && window.CG_MANAGED.config) {
        for (const key in window.CG_MANAGED.config) {
            if (window.CG_CONFIG[key] === undefined) {
                window.CG_CONFIG[key] = window.CG_MANAGED.config[key];
            }
        }
    }

    // ========================================================================
    // SCRIPT LOADER
    // ========================================================================

    if (document.getElementById("cg_prod_bundle")) {
        console.log("[CG] PROD bundle already loaded; skipping");
        return;
    }

    // Read release configuration from managed block
    const release = (window.CG_MANAGED && window.CG_MANAGED.release) || {
        channel: "prod",
        version: "v1.0.2",
        source: "github_release"
    };

    const script = document.createElement("script");
    script.id = "cg_prod_bundle";

    // Determine script URL based on source
    if (release.source === "github_release") {
        script.src = `https://github.com/morenet-canvas/CustomizedGradebook/releases/download/${release.version}/customGradebookInit.js`;
    } else if (release.source === "pages") {
        const cacheBuster = release.version || Date.now();
        script.src = `https://morenet-canvas.github.io/CustomizedGradebook/dist/prod/customGradebookInit.js?v=${cacheBuster}`;
    } else {
        console.error("[CG] Unknown release source:", release.source);
        return;
    }

    script.onload = () => console.log(`[CG] Loaded customGradebookInit.js (PROD ${release.version})`);
    script.onerror = () => console.error("[CG] Failed to load customGradebookInit.js (PROD)");
    document.head.appendChild(script);
})();

/* BEGIN CG MANAGED CODE */
/* Generated: 2026-02-04T00:00:00.000Z */
/* Purpose: Version and configuration management for production loader */

window.CG_MANAGED = window.CG_MANAGED || {};

// Release configuration
window.CG_MANAGED.release = {
    channel: "prod",
    version: "v1.0.2",
    source: "github_release"
};

// Configuration overrides (optional - defaults are defined in loader)
window.CG_MANAGED.config = {};

/* END CG MANAGED CODE */